name: Review solutions assignment
description: Assign a piece of technical coursework
title: "[TECH ED] Review solutions for last week's coursework"
labels: [Tech Ed, 🏕 Priority Mandatory]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to assign this coursework! 

        To support our trainees with planning and prioritising their own learning journey, we want our coursework assignments to be more informative. 
        We don't just want to tell them what to do, we want to tell them stuff like:
        - why we are doing it
        - what it's "for" (problem-solving, debugging, etc)
        - how long they should spend on it, maximum
        - how to get help 
        - how to review it with answers 
        - how to get it reviewed from mentors and peers
  - type: textarea
    attributes:
      label: Why are we doing this?
      description: Clearly explain the purpose of this assignment
      value: |
        You'll need to regularly check solutions to evaluate your understanding. 
        However, you must attempt the activities first before you use the solutions.
        You can find the solutions for all the assignments in this repo's `solutions` branch.
    validations:
      required: true
  - type: input
    attributes:
      label: Maximum time in hours
      description: (Tech has max 16 per week total)
      value: "0.5"
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to get help
      description: State simply how trainees can get help with this assignment
      placeholder: |
        Share your blockers in your class channel
        https://syllabus.codeyourfuture.io/guides/asking-questions
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give more context

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**

        Please now complete this ticket by filling in the options on the sidebar.

        1. Update labels
        - priority -- is this coursework key, mandatory, or stretch? Pick one.
        - size -- help trainees plan their time with rough estimation. Pick one
        - topics -- add all that seem relevant to you. 
        2. Add to milestone
        - week 1,2,3,4

        Once your ticket is complete, you may like to add it to the example project board attached to this repo.
        This is so you understand how trainees will use your work. Nobody has built a board copier yet, so trainees will be doing this step themselves.
